package org.schabi.newpipe.util

import android.content.Context
import android.view.View
import android.view.View.GONE
import android.view.View.INVISIBLE
import android.view.View.VISIBLE
import android.widget.Spinner
import androidx.collection.SparseArrayCompat
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.filters.MediumTest
import androidx.test.internal.runner.junit4.statement.UiThreadStatement
import org.junit.Assert
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import org.schabi.newpipe.R
import org.schabi.newpipe.extractor.MediaFormat
import org.schabi.newpipe.extractor.downloader.Response
import org.schabi.newpipe.extractor.stream.AudioStream
import org.schabi.newpipe.extractor.stream.Stream
import org.schabi.newpipe.extractor.stream.SubtitlesStream
import org.schabi.newpipe.extractor.stream.VideoStream
import org.schabi.newpipe.util.StreamItemAdapter.StreamInfoWrapper

@MediumTest
@RunWith(AndroidJUnit4::class)
class StreamItemAdapterTest {
    private lateinit var context: Context
    private lateinit var spinner: Spinner

    @Before
    fun setUp() {
        context = ApplicationProvider.getApplicationContext()
        UiThreadStatement.runOnUiThread {
            spinner = Spinner(context)
        }
    }

    @Test
    fun videoStreams_noSecondaryStream() {
        val adapter = StreamItemAdapter<VideoStream, AudioStream>(
            getVideoStreams(true, true, true, true)
        )

        spinner.adapter = adapter
        assertIconVisibility(spinner, 0, VISIBLE, VISIBLE)
        assertIconVisibility(spinner, 1, VISIBLE, VISIBLE)
        assertIconVisibility(spinner, 2, VISIBLE, VISIBLE)
        assertIconVisibility(spinner, 3, VISIBLE, VISIBLE)
    }

    @Test
    fun videoStreams_hasSecondaryStream() {
        val adapter = StreamItemAdapter(
            getVideoStreams(false, true, false, true),
            getAudioStreams(false, true, false, true)
        )

        spinner.adapter = adapter
        assertIconVisibility(spinner, 0, GONE, GONE)
        assertIconVisibility(spinner, 1, GONE, GONE)
        assertIconVisibility(spinner, 2, GONE, GONE)
        assertIconVisibility(spinner, 3, GONE, GONE)
    }

    @Test
    fun videoStreams_Mixed() {
        val adapter = StreamItemAdapter(
            getVideoStreams(true, true, true, true, true, false, true, true),
            getAudioStreams(false, true, false, false, false, true, true, true)
        )

        spinner.adapter = adapter
        assertIconVisibility(spinner, 0, VISIBLE, VISIBLE)
        assertIconVisibility(spinner, 1, GONE, INVISIBLE)
        assertIconVisibility(spinner, 2, VISIBLE, VISIBLE)
        assertIconVisibility(spinner, 3, VISIBLE, VISIBLE)
        assertIconVisibility(spinner, 4, VISIBLE, VISIBLE)
        assertIconVisibility(spinner, 5, GONE, INVISIBLE)
        assertIconVisibility(spinner, 6, GONE, INVISIBLE)
        assertIconVisibility(spinner, 7, GONE, INVISIBLE)
    }

    @Test
    fun subtitleStreams_noIcon() {
        val adapter = StreamItemAdapter<SubtitlesStream, Stream>(
            StreamItemAdapter.StreamInfoWrapper(
                (0 until 5).map {
                    SubtitlesStream.Builder()
                        .setContent("https://example.com", true)
                        .setMediaFormat(MediaFormat.SRT)
                        .setLanguageCode("pt-BR")
                        .setAutoGenerated(false)
                        .build()
                },
                context
            )
        )
        spinner.adapter = adapter
        for (i in 0 until spinner.count) {
            assertIconVisibility(spinner, i, GONE, GONE)
        }
    }

    @Test
    fun audioStreams_noIcon() {
        val adapter = StreamItemAdapter<AudioStream, Stream>(
            StreamItemAdapter.StreamInfoWrapper(
                (0 until 5).map {
                    AudioStream.Builder()
                        .setId(Stream.ID_UNKNOWN)
                        .setContent("https://example.com/$it", true)
                        .setMediaFormat(MediaFormat.OPUS)
                        .setAverageBitrate(192)
                        .build()
                },
                context
            )
        )
        spinner.adapter = adapter
        for (i in 0 until spinner.count) {
            assertIconVisibility(spinner, i, GONE, GONE)
        }
    }

    @Test
    fun retrieveMediaFormatFromFileTypeHeaders() {
        val streams = getIncompleteAudioStreams(5)
        val wrapper = StreamInfoWrapper(streams, context)

        val invalidResponse1 = getResponse(mapOf(Pair("content-length", "mp3")))
        val invalidResponse2 = getResponse(mapOf(Pair("file-type", "mp0")))
        val amazonResponse = getResponse(mapOf(Pair("x-amz-meta-file-type", "aiff")))
        val normalResponse = getResponse(mapOf(Pair("file-type", "mp3")))

        assertFalse(
            "invalid header returns valid value", StreamInfoWrapper
                .retrieveMediaFormatFromFileTypeHeaders(streams[0], wrapper, invalidResponse1)
        )
        assertNull("Media format extracted although stated otherwise", wrapper.getFormat(0))

        assertFalse(
            "invalid file type returns valid MediaFormat", StreamInfoWrapper
                .retrieveMediaFormatFromFileTypeHeaders(streams[1], wrapper, invalidResponse2)
        )
        assertNull("Media format extracted although file type is invalid", wrapper.getFormat(1))

        assertTrue(
            "file-type header was not recognized", StreamInfoWrapper
                .retrieveMediaFormatFromFileTypeHeaders(streams[2], wrapper, amazonResponse)
        )
        assertEquals("Wrong media format extracted", MediaFormat.AIFF, wrapper.getFormat(2))

        assertTrue(
            "file-type header was not recognized", StreamInfoWrapper
                .retrieveMediaFormatFromFileTypeHeaders(streams[3], wrapper, normalResponse)
        )
        assertEquals("Wrong media format extracted", MediaFormat.MP3, wrapper.getFormat(3))

        wrapper.resetInfo()
    }

    @Test
    fun retrieveMediaFormatFromContentDispositionHeader() {
        val streams = getIncompleteAudioStreams(7)
        val wrapper = StreamInfoWrapper(streams, context)
        val retrieveMediaFormat = { stream: AudioStream, response: Response ->
            StreamInfoWrapper<AudioStream>::retrieveMediaFormatFromContentDispositionHeader(stream, wrapper, response)
        }


        val helper = AssertionHelper(streams, wrapper, retrieveMediaFormat)

        helper.assertInvalidResponse(getResponse(mapOf(Pair("content-length", "mp3"))), 0)
        helper.assertInvalidResponse(getResponse(mapOf(Pair("Content-Disposition",
                "name=\"train.png\""))), 1)
        helper.assertInvalidResponse(getResponse(mapOf(Pair("Content-Disposition",
                "form-data; name=\"data.csv\""))), 2)
        helper.assertInvalidResponse(getResponse(mapOf(Pair("Content-Disposition",
                "form-data; name=\"fieldName\"; filename=\"filename.jpg\""))), 3)

        helper.assertValidResponse(getResponse(mapOf(Pair("Content-Disposition",
                "name=\"train.ogg\""))), 4, MediaFormat.OGG)
        helper.assertValidResponse(getResponse(mapOf(Pair("Content-Disposition",
                "form-data; name=\"audio.flac\""))), 5, MediaFormat.FLAC)
        helper.assertValidResponse(getResponse(mapOf(Pair("Content-Disposition",
                "form-data; name=\"audio.aiff\"; filename=\"audio.aiff\""))), 6, MediaFormat.AIFF)
    }

    /**
     * @return a list of video streams, in which their video only property mirrors the provided
     * [videoOnly] vararg.
     */
    private fun getVideoStreams(vararg videoOnly: Boolean) =
        StreamItemAdapter.StreamInfoWrapper(
            videoOnly.map {
                VideoStream.Builder()
                    .setId(Stream.ID_UNKNOWN)
                    .setContent("https://example.com", true)
                    .setMediaFormat(MediaFormat.MPEG_4)
                    .setResolution("720p")
                    .setIsVideoOnly(it)
                    .build()
            },
            context
        )

    /**
     * @return a list of audio streams, containing valid and null elements mirroring the provided
     * [shouldBeValid] vararg.
     */
    private fun getAudioStreams(vararg shouldBeValid: Boolean) =
        getSecondaryStreamsFromList(
            shouldBeValid.map {
                if (it) {
                    AudioStream.Builder()
                        .setId(Stream.ID_UNKNOWN)
                        .setContent("https://example.com", true)
                        .setMediaFormat(MediaFormat.OPUS)
                        .setAverageBitrate(192)
                        .build()
                } else {
                    null
                }
            }
        )

    private fun getIncompleteAudioStreams(size: Int): List<AudioStream> {
        val list = ArrayList<AudioStream>(size)
        for (i in 1..size) {
            list.add(
                AudioStream.Builder()
                    .setId(Stream.ID_UNKNOWN)
                    .setContent("https://example.com/$i", true)
                    .build()
            )
        }
        return list
    }

    /**
     * Checks whether the item at [position] in the [spinner] has the correct icon visibility when
     * it is shown in normal mode (selected) and in dropdown mode (user is choosing one of a list).
     */
    private fun assertIconVisibility(
        spinner: Spinner,
        position: Int,
        normalVisibility: Int,
        dropDownVisibility: Int
    ) {
        spinner.setSelection(position)
        spinner.adapter.getView(position, null, spinner).run {
            Assert.assertEquals(
                "normal visibility (pos=[$position]) is not correct",
                findViewById<View>(R.id.wo_sound_icon).visibility,
                normalVisibility,
            )
        }
        spinner.adapter.getDropDownView(position, null, spinner).run {
            Assert.assertEquals(
                "drop down visibility (pos=[$position]) is not correct",
                findViewById<View>(R.id.wo_sound_icon).visibility,
                dropDownVisibility
            )
        }
    }



    /**
     * Helper function that builds a secondary stream list.
     */
    private fun <T : Stream> getSecondaryStreamsFromList(streams: List<T?>) =
        SparseArrayCompat<SecondaryStreamHelper<T>?>(streams.size).apply {
            streams.forEachIndexed { index, stream ->
                val secondaryStreamHelper: SecondaryStreamHelper<T>? = stream?.let {
                    SecondaryStreamHelper(
                        StreamItemAdapter.StreamInfoWrapper(streams, context),
                        it
                    )
                }
                put(index, secondaryStreamHelper)
            }
        }

    private fun getResponse(headers: Map<String, String>): Response {
        val listHeaders = HashMap<String, List<String>>()
        headers.forEach { entry ->
            listHeaders[entry.key] = listOf(entry.value)
        }
        return Response(200, null, listHeaders, "", "")
    }

    companion object {
        fun a(a: String): Boolean {
            return a.isEmpty()
        }
    }

    class AssertionHelper<T: Stream>(
            private val streams: List<T>,
            private val wrapper: StreamInfoWrapper<T>,
            private val retrieveMediaFormat: (stream: T, response: Response) -> Boolean) {

        /**
         * Assert that an invalid response does not result in wrongly extracted
         */
        fun assertInvalidResponse(
                response: Response,
                index: Int) {
            assertFalse("invalid header returns valid value",
                    retrieveMediaFormat(streams[index], response))
            assertNull("Media format extracted although stated otherwise", wrapper.getFormat(index))
        }
        fun assertValidResponse(
                response: Response,
                index: Int,
                format: MediaFormat) {
            assertTrue(
                    "header was not recognized", StreamInfoWrapper
                    .retrieveMediaFormatFromContentDispositionHeader(streams[index], wrapper, response)
            )
            assertEquals("Wrong media format extracted", format, wrapper.getFormat(index))
        }
    }
}
