name: Build Pull Requests

on:
  pull_request:
    branches: # we might want to add all branches here
      - 'master'
      - 'dev'

jobs:
  build:
    name: Build project & generate APK
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8

      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: app/build/outputs/apk/debug/*.apk

      - name: Create comment linking to the artifact
        uses: thollander/actions-comment-pull-request@master
        with:
          message: 'The APK was build successfully. You can find it here: https://github.com/TobiGr/NewPipe/actions/runs/${{github.run_id}}#artifacts'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: do ugly things
        uses: actions/github-script@v3
        with:
          githubtoken: ${{ secrets.GITHUB_TOKEN }}
          #script: |
          #  github.issues.createComment({
          #    issue_number: context.issue.number,
          #    owner: context.repo.owner,
          #    repo: context.repo.repo,
          #    body: 'Script: The APK was build successfully. You can find it here: https://github.com/TobiGr/NewPipe/actions/runs/${{github.run_id}}'
          #  })
          script: echo $githubToken | sha512sum